### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by teamon** [Recruitee/bunny#1]
### core
- [x] exponential backoff
- [x] respect retry limit and put to dead queue
- [x] handle connection unavailable at start
- [x] handle connection lost when waiting for messages
- [x] handle connection lost while processing
- [x] handle connection lost after processing, before ack
- [x] handle job process exit
- [ ] handle queue creation error
- [ ] decoding helpers
- [x] pass meta to `process/2`
- [ ] allow hooking up metrics
- [ ] expose current status (succeeded/failed count, running jobs)
- [ ] retry dead messages api

### docs
- [ ] README: how it works
- [ ] README: configuration (static & runtime)
